# Generated by Django 2.1.7 on 2019-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
