# Generated by Django 2.1.7 on 2019-03-27 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20190313_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 18, 12, 9, 845528, tzinfo=utc)),
        ),
    ]
