"""
Django settings for chat project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kk)k4#7ul8g*=kw=at!i0i3tswaa7cbe04!a(^i^5(mycaitpq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'chat.apps.myauth',
    'chat.apps.core',
    'chat.apps.chat.apps.ChatConfig',

    'rest_framework',
    'channels',
    'djoser',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'myauth.User'

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'



# Channels

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

ASGI_APPLICATION = "chat.routing.application"

##### rest ###########

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
         'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2,
    'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.SearchFilter',)
}

REST_CALLBACK = {
    'msg_create': 'send_message',
    'room_create': 'open_room'
}

DJOSER = {
        'SERIALIZERS': {
            'user': 'chat.apps.myauth.serializer.UserSerializer',
            },
        'PERMISSIONS': {
            'user': ['rest_framework.permissions.AllowAny']
        },
        'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': ['http://localhost:8000/'],
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'chat.apps.myauth.strategy.ExpTokenStrategy',
    }

###################### social-auth ############

AUTHENTICATION_BACKENDS = (
   'social_core.backends.vk.VKOAuth2',
    'social_core.backends.github.GithubOAuth2',

   'django.contrib.auth.backends.ModelBackend',

)

# SIMPLE_JWT = {
#     'ROTATE_REFRESH_TOKENS': True,
# }


SOCIAL_AUTH_VK_OAUTH2_KEY = '6921030'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'xIixuPRzsOhrWx1HLuXB'

SOCIAL_AUTH_GITHUB_KEY = 'fe3c7725b26a2e6d8830'
SOCIAL_AUTH_GITHUB_SECRET = 'e2fb61a7526c1f86b3563a86732ea75b05d6ebdc'

DRFSO2_PROPRIETARY_BACKEND_NAME = 'VKOAuth2'

