# Generated by Django 2.1.7 on 2019-03-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190313_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='room',
            name='group_name',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
