# Generated by Django 2.1.7 on 2019-04-03 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190317_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-last_change']},
        ),
        migrations.AddField(
            model_name='room',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
