# Generated by Django 2.1.7 on 2019-04-04 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20190403_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='who_viewed_it',
            field=models.ManyToManyField(related_name='viewed_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
